CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(300) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at DATETIME NOT NULL
);
